chore(pipeline): stop pipeline build stage if manifest validation failed

diff --git a/internal/pkg/template/templates/cicd/buildspec.yml b/internal/pkg/template/templates/cicd/buildspec.yml
--- a/internal/pkg/template/templates/cicd/buildspec.yml
+++ b/internal/pkg/template/templates/cicd/buildspec.yml
@@ -56,9 +56,21 @@ phases:
           tag=$(sed 's/:/-/g' <<<"${CODEBUILD_BUILD_ID##*:}-${env}" | rev | cut -c 1-128 | rev)
           for svc in $svcs; do
           ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag;
+      # Check if the params file is empty. If so, echo error msg and exit.
+          [ -s ./infrastructure/$svc-$env.params.json ]
+          if [ $? -ne 0 ]; then
+            echo "Cloudformation stack and config files were not generated. Please check build logs for a manifest validation error message." 1>&2;
+            exit 1;
+          fi
           done;
           for job in $jobs; do
           ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag;
+        # Check if the params file is empty. If so, echo error msg and exit.
+          [ -s ./infrastructure/$job-$env.params.json ]
+          if [ $? -ne 0 ]; then
+            echo "Cloudformation stack and config files were not generated. Please check build logs for a manifest validation error message." 1>&2;
+            exit 1;
+          fi
           done;
         done;
       - ls -lah ./infrastructure
