chore: update usage

diff --git a/scripts/run-e2e b/scripts/run-e2e
--- a/scripts/run-e2e
+++ b/scripts/run-e2e
@@ -2,17 +2,19 @@
 set -e
 
 usage() {
-	echo "run-e2e <test suite>"
-	echo "ex: run-e2e addons"
+	echo "Usage: scripts/run-e2e <test suite>"
+	echo "ex: scripts/run-e2e addons"
+	echo ""
 	echo "Runs the specified test suite."
 	echo ""
 	echo "------------------------    Configuration    -------------------------"
-	echo "In addition to the \"test suite\" positional argument, this script"
-	echo "is controlled by the following environment variables."
+	echo "In addition to the \"test suite\" positional argument, this script is"
+	echo "controlled by the following environment variables."
+	echo ""
 	echo "  DOCKERHUB_USERNAME (Required) The username for the Dockerhub account."
-	echo "  DOCKERHUB_TOKEN	   (Required) A Dockerhub API token."
-	echo "  AWS_DIR            Full path to directory containing long-lived AWS creds to"
-	echo "                       mount into the Docker container."
+	echo "  DOCKERHUB_TOKEN    (Required) A Dockerhub API token."
+	echo "  AWS_DIR            Full path to directory containing long-lived AWS "
+	echo "                       credentials to mount into the Docker container."
 }
 
 if [[ $# -eq 0 ]]; then
@@ -31,10 +33,11 @@ if [[ -z ${DOCKERHUB_USERNAME} ]]; then
 fi
 
 if [[ -z ${AWS_DIR} ]]; then
-	AWS_DIR=${HOME}/aws
+	echo "AWS_DIR is unset; defaulting to ${HOME}/.aws"
+	AWS_DIR=${HOME}/.aws
 fi
 
 
-make build-e2e
-echo "Running test suite $@ with credentials sourced from $AWS_DIR and Dockerhub user $DOCKERHUB_USERNAME"
-docker run --privileged -v ${AWS_DIR}:/home/.aws -e "HOME=/home" -e "DOCKERHUB_TOKEN=$DOCKERHUB_TOKEN" -e "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" -e "TEST_SUITE=$@" copilot/e2e:latest
+make build-e2e || exit 1
+echo "Running test suite $@ with credentials sourced from ${AWS_DIR} and Dockerhub user ${DOCKERHUB_USERNAME}"
+docker run --privileged -v ${AWS_DIR}:/home/.aws -e "HOME=/home" -e "DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}" -e "DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}" -e "TEST_SUITE=$@" copilot/e2e:latest
